### ISSUE TITLE
Ojo con la ortografía

### ISSUE THREAD

**Issue by cgosorio** [gonmurillo/TFG_EDVR#2]
Ojo con la ortografía y la gramática y con la escritura en general. En el cuaderno del commit https://github.com/gonmurillo/TFG_EDVR/commit/7695462ce270ab887875354422f53e8000614741 hay un montón de errores de ortografía:

Garcıa ⭆ García
participntes ⭆ participantes
super-resolucion ⭆ super-resolución
herramienta conteniada ⭆ herramienta contenida
imágen ⭆ imagen
pevios ⭆ previos
siguentes ⭆ siguientes
nustras ⭆ nuestras
parametro ⭆ parámetro
se ha usdo ⭆ se ha usado
nustros experimentos ⭆ nuestros experimentos
preentrenado ⭆ pre-entrenado
Metricas ⭆ Métricas
se han unsado ⭆ se han usado
acronimo ⭆ acrónimo
resolucón de víedos ⭆ resolución de vídeos
super resolucion ⭆ super resolución
La cita perteece ⭆ La cita pertenece
opcioines de ejecución ⭆ opciones de ejecución
debeida a las limitaciones ⭆ debida a las limitaciones
Poner aqui ⭆ Poner aquí
baja resolucion ⭆ baja resolución
GPU's  ⭆ GPU

Sobre esta última, en español los acrónimos en plural no llevan la s, puedes decir «las GPU», pero no «las GPUs». En inglés el «'s» es el genitivo sajón, no se usa para los plurales. Así que tampoco podrías decir en inglés «you need at least two GPU's», si acaso «you need at least two GPUs».

**Comment by gonmurillo** [comment]
Ya esta corregido, gracias César a partir de ahora tendré más cuidado.
